version: '3.9'
services:
  ssh.cyrhades.fr:
    build: ./.docker/ssh
  webssh.cyrhades.fr:
    build: ./.docker/webssh
    ports:
      - ${PORT}:8888
  intro-to-pwntools.cyrhades.fr:
    image: anssi/fcsc2025-misc-intro-to-pwntools:latest
    ports:
      - ${PORT_SSH}:4000
